exports.radioStations = [
    "https://streams.ilovemusic.de/iloveradio14.mp3",
    "https://baseradiode.stream.laut.fm/baseradiode",
    "https://streams.ilovemusic.de/iloveradio17.mp3",
    "https://streams.ilovemusic.de/iloveradio2.mp3",
    "https://streams.ilovemusic.de/iloveradio16.mp3",
    "https://streams.ilovemusic.de/iloveradio3.mp3",
    "https://streams.ilovemusic.de/iloveradio14.mp3",
    "https://streams.ilovemusic.de/iloveradio13.mp3",
    "https://stream-mz.planetradio.co.uk/net2national.mp3",
    "http://icy-e-bab-02-gos.sharp-stream.com/absoluteradio.mp3",
    "http://ais.absoluteradio.co.uk/absolute70s.mp3",
    "http://ais.absoluteradio.co.uk/absolute80s.mp3",
    "http://ais.absoluteradio.co.uk/absolute90s.mp3",
    "http://ais.absoluteradio.co.uk/absolute00s.mp3",
    "http://icy-e-bab-04-cr.sharp-stream.com/absoluteclassicrock.mp3",
    "http://radio886.fluidstream.eu/886_live.mp3",
    "http://loadbalancing.topradio.be/topradio.mp3",
    "http://cdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3",
    "https://streams.ilovemusic.de/iloveradio104.mp3",
    "http://8903.brasilstream.com.br:8903/stream?1618706382258",
    "https://9554.brasilstream.com.br/stream?1618706821810",
    "https://server01.ouvir.radio.br:8042/stream?1618707015340",
    "https://c5.radioboss.fm:18224/stream",
    "https://vip2.fastcast4u.com/proxy/classicrockdoug?mp=/1",
    "https://n1ea-e2.revma.ihrhls.com/zc1469?rj-ttl=5&rj-tok=AAABeOKLG9IArEWSocBcSUogkQ",
]
exports.radioStationsName = [
    "Standard-Radio",
    "Base-Radio",
    "Chill-Radio",
    "Dance-Radio",
    "Greatest-hits-Radio",
    "Hip-hop-Radio",
    "Party-Radio",
    "Us-Rap-Radio",
    "Greatest-hits-Radio-2",
    "Absolut-Radio",
    "Absolut-70s-Radio",
    "Absolut-80s-Radio",
    "Absolut-90s-Radio",
    "Absolut-2000s-Radio",
    "Absolut-Classic-Rock",
    "88.6-Radio",
    "Top-Radio",
    "NRJ-Radio",
    "Color-Music-Radio",
    "Rádio Itatiaia",
    "Rádio FM 98",
    "Rádio Jovem Pan 107.3 FM",
    "American Road Radio",
    "Classic Rock Florida",
    "Rádio Z100 - 100.3 FM"
]